#pragma once

const int MAX_ARRAY_SIZE = 1024;
const char ROOMS_FILE_NAME[MAX_ARRAY_SIZE] = "rooms.dat";

const int MIN_RESERVATIONS_FOR_BEIGN_GOLD = 6;
const int MIN_RESERVATIONS_FOR_BEIGN_PLATINUM = 20;

const int PEOPLE_CAPACITY_APARTMENT = 4;
const int INITIAL_PRICE_APARTMENT = 120;

const int PEOPLE_CAPACITY_DOUBLE_ROOM = 2;
const int INITIAL_PRICE_DOUBLE_ROOM = 70;

const int PEOPLE_CAPACITY_CONFERENCE_ROOM = 50;
const int INITIAL_PRICE_CONFERENCE_ROOM = 2000;


const int PEOPLE_CAPACITY_LUXURY_ROOM = 2;
const int INITIAL_PRICE_LUXURY_ROOM = 140;